<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\PhieuFlow.Core\PhieuFlow.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazicons" Version="4.0.21" />
    <PackageReference Include="Blazicons.Lucide" Version="3.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
