// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhieuFlow.Persistence;

#nullable disable

namespace PhieuFlow.Persistence.Migrations
{
    [DbContext(typeof(HubDbContext))]
    [Migration("20260907123230_AddProcessedMessages")]
    partial class AddProcessedMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhieuFlow.Core.Entities.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Forms", (string)null);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormPage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FormVersionId");

                    b.ToTable("FormPages", (string)null);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FormVersionNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("FormVersionId");

                    b.HasIndex("FormId", "FormVersionNumber");

                    b.ToTable("FormSubmissions", (string)null);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("FormId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("FormVersions", (string)null);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId");

                    b.ToTable("ProcessedMessages", (string)null);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FormPageId");

                    b.ToTable("Questions", (string)null);

                    b.HasDiscriminator<string>("QuestionType").HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChoiceQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceQuestionId");

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.SubmissionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<Guid>("FormSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FormSubmissionId");

                    b.ToTable("SubmissionAnswers", (string)null);

                    b.HasDiscriminator<string>("AnswerType").HasValue("SubmissionAnswer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.CalendarQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.Question");

                    b.Property<DateOnly?>("MaxDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MinDate")
                        .HasColumnType("date");

                    b.HasDiscriminator().HasValue("Calendar");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.CheckboxQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.Question");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasDiscriminator().HasValue("Checkbox");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.ChoiceQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.Question");

                    b.HasDiscriminator().HasValue("ChoiceQuestion");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.NumberQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.Question");

                    b.Property<decimal?>("Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasDiscriminator().HasValue("Number");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.TextAreaQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.Question");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("TextArea");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.BooleanSubmissionAnswer", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.SubmissionAnswer");

                    b.Property<bool>("Checked")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Boolean");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.OptionSubmissionAnswer", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.SubmissionAnswer");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue("Option");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.ValueSubmissionAnswer", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.SubmissionAnswer");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasDiscriminator().HasValue("Value");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.CheckBoxGroupQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.ChoiceQuestion");

                    b.Property<int?>("MaxSelections")
                        .HasColumnType("int");

                    b.Property<int?>("MinSelections")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("CheckBoxGroup");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.DropDownQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.ChoiceQuestion");

                    b.HasDiscriminator().HasValue("DropDown");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.RadioButtonQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.ChoiceQuestion");

                    b.HasDiscriminator().HasValue("RadioButton");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormPage", b =>
                {
                    b.HasOne("PhieuFlow.Core.Entities.FormVersion", "FormVersion")
                        .WithMany("Pages")
                        .HasForeignKey("FormVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormVersion");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormSubmission", b =>
                {
                    b.HasOne("PhieuFlow.Core.Entities.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhieuFlow.Core.Entities.FormVersion", "FormVersion")
                        .WithMany()
                        .HasForeignKey("FormVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("FormVersion");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormVersion", b =>
                {
                    b.HasOne("PhieuFlow.Core.Entities.Form", "Form")
                        .WithMany("Versions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.Question", b =>
                {
                    b.HasOne("PhieuFlow.Core.Entities.FormPage", "FormPage")
                        .WithMany("Questions")
                        .HasForeignKey("FormPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormPage");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.QuestionOption", b =>
                {
                    b.HasOne("PhieuFlow.Core.Entities.ChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("ChoiceQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.SubmissionAnswer", b =>
                {
                    b.HasOne("PhieuFlow.Core.Entities.FormSubmission", "FormSubmission")
                        .WithMany("Answers")
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormSubmission");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.Form", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormPage", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormVersion", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.ChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
