// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhieuFlow.Hub.Data;

#nullable disable

namespace PhieuFlow.Hub.Data.Migrations
{
    [DbContext(typeof(HubDbContext))]
    partial class HubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhieuFlow.Core.Entities.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Forms", (string)null);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormPage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormPages", (string)null);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FormPageId");

                    b.ToTable("Questions", (string)null);

                    b.HasDiscriminator<string>("QuestionType").HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChoiceQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceQuestionId");

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.CalendarQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.Question");

                    b.Property<DateOnly?>("MaxDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MinDate")
                        .HasColumnType("date");

                    b.HasDiscriminator().HasValue("Calendar");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.CheckboxQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.Question");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasDiscriminator().HasValue("Checkbox");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.ChoiceQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.Question");

                    b.HasDiscriminator().HasValue("ChoiceQuestion");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.NumberQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.Question");

                    b.Property<decimal?>("Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasDiscriminator().HasValue("Number");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.TextAreaQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.Question");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("TextArea");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.CheckBoxGroupQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.ChoiceQuestion");

                    b.Property<int?>("MaxSelections")
                        .HasColumnType("int");

                    b.Property<int?>("MinSelections")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("CheckBoxGroup");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.DropDownQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.ChoiceQuestion");

                    b.HasDiscriminator().HasValue("DropDown");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.RadioButtonQuestion", b =>
                {
                    b.HasBaseType("PhieuFlow.Core.Entities.ChoiceQuestion");

                    b.HasDiscriminator().HasValue("RadioButton");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormPage", b =>
                {
                    b.HasOne("PhieuFlow.Core.Entities.Form", "Form")
                        .WithMany("Pages")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.Question", b =>
                {
                    b.HasOne("PhieuFlow.Core.Entities.FormPage", "FormPage")
                        .WithMany("Questions")
                        .HasForeignKey("FormPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormPage");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.QuestionOption", b =>
                {
                    b.HasOne("PhieuFlow.Core.Entities.ChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("ChoiceQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.Form", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.FormPage", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PhieuFlow.Core.Entities.ChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
